name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Code analysis
        run: npm run analysis

      - name: Performance testing
        run: npm run performance

      - name: Dependency audit
        run: npm run dependency_audit
