name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run E2E tests
      run: npm run e2e

    - name: Run Prettier Analysis
      run: npm run analysis

    - name: Run Performance Tests
      run: npm run performance

    - name: Run Dependency Audit
      run: npm run dependency_audit
